lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  -'12'
git:
  depth:3
script:
  - yarn build
notifications:
  email:
    - imanolsuarez98@gmail.com
    # PUEDEN HABER MAS DE 1 CORREO ELECTRONICO
    on_success: always
    on_failure: always
    # MANDA MAIL CUANDO ES EXITO O FALLA
deploy:
  provider: pages
  skip_cleanup:true
  keep_history:true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message:'Deploy del proyecto'
  on:
    branch: master
